version: 0.1

phases:
  post_build:
    commands:
      - aws --region us-east-1 s3 sync s3://codepipeline-us-east-1-394769782722/Troop161_Web/dist s3://qa.troop161shoreham.org/ --acl=public-read --delete

artifacts:
  files:
    - build*/**
discard-paths: yes
